import Foundation
import RoomPlan
import simd

enum ModelExportService {
    /// Exports a captured room as USDZ and PLY into a temporary directory.
    static func makeExportFiles(
        room: CapturedRoom,
        roomName: String
    ) throws -> [URL] {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("RoomModel-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let safeName = sanitizeFilename(roomName.isEmpty ? "room" : roomName)
        var files: [URL] = []

        let usdzURL = directory.appendingPathComponent("\(safeName).usdz")
        try room.export(to: usdzURL, exportOptions: .model)
        files.append(usdzURL)

        let plyURL = directory.appendingPathComponent("\(safeName).ply")
        try PLYExporter.write(room: room, to: plyURL)
        files.append(plyURL)

        return files
    }

    static func sanitizeFilename(_ name: String) -> String {
        var safe = String(name.unicodeScalars.filter { $0.value >= 0x20 && $0.value != 0x7F })
        safe = safe
            .replacingOccurrences(of: " ", with: "-")
            .lowercased()
        for character in ["/", "\\", ":", "*", "?", "\"", "<", ">", "|"] {
            safe = safe.replacingOccurrences(of: character, with: "-")
        }
        while safe.hasPrefix(".") { safe = String(safe.dropFirst()) }
        while safe.contains("--") {
            safe = safe.replacingOccurrences(of: "--", with: "-")
        }
        if safe.count > 60 { safe = String(safe.prefix(60)) }
        if safe.trimmingCharacters(in: .punctuationCharacters).isEmpty { safe = "room" }
        return safe
    }
}

enum PLYExporter {
    struct Vertex {
        let x: Double
        let y: Double
        let z: Double
        let r: UInt8
        let g: UInt8
        let b: UInt8
    }

    static func write(room: CapturedRoom, to url: URL) throws {
        var vertices: [Vertex] = []
        var faces: [[Int]] = []

        // Floor polygons
        for floor in room.floors {
            let corners = floor.polygonCorners.map {
                RoomDataProcessor.transformCornerToWorld($0, transform: floor.transform)
            }
            guard corners.count >= 3 else { continue }
            let base = vertices.count
            for corner in corners {
                vertices.append(Vertex(
                    x: Double(corner.x),
                    y: Double(corner.y),
                    z: Double(corner.z),
                    r: 220, g: 224, b: 230
                ))
            }
            appendTriangulatedFan(base: base, count: corners.count, to: &faces)
        }

        // Walls, doors, windows and openings as rectangles
        for wall in room.walls {
            appendSurface(vertices: &vertices, faces: &faces, surface: wall, color: (245, 248, 252))
        }
        for door in room.doors {
            appendSurface(vertices: &vertices, faces: &faces, surface: door, color: (176, 196, 220))
        }
        for window in room.windows {
            appendSurface(vertices: &vertices, faces: &faces, surface: window, color: (120, 180, 235))
        }
        for opening in room.openings {
            appendSurface(vertices: &vertices, faces: &faces, surface: opening, color: (200, 160, 120))
        }

        // Objects as boxes
        for object in room.objects {
            appendBox(vertices: &vertices, faces: &faces, object: object)
        }

        guard !vertices.isEmpty else {
            throw NSError(
                domain: "PLYExporter",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "房间没有可导出的几何数据"]
            )
        }

        var text = "ply\n"
        text += "format ascii 1.0\n"
        text += "comment generated by RoboScan\n"
        text += "element vertex \(vertices.count)\n"
        text += "property float x\n"
        text += "property float y\n"
        text += "property float z\n"
        text += "property uchar red\n"
        text += "property uchar green\n"
        text += "property uchar blue\n"
        text += "element face \(faces.count)\n"
        text += "property list uchar int vertex_indices\n"
        text += "end_header\n"

        for vertex in vertices {
            text += "\(format(vertex.x)) \(format(vertex.y)) \(format(vertex.z)) \(vertex.r) \(vertex.g) \(vertex.b)\n"
        }
        for face in faces {
            text += "\(face.count) \(face.map(String.init).joined(separator: " "))\n"
        }

        try text.write(to: url, atomically: true, encoding: .utf8)
    }

    private static func appendSurface(
        vertices: inout [Vertex],
        faces: inout [[Int]],
        surface: CapturedRoom.Surface,
        color: (UInt8, UInt8, UInt8)
    ) {
        let w = Double(surface.dimensions.x)
        let h = Double(surface.dimensions.y)
        guard w > 0.001, h > 0.001 else { return }

        let local: [SIMD3<Float>] = [
            SIMD3(0, 0, 0),
            SIMD3(Float(w), 0, 0),
            SIMD3(Float(w), Float(h), 0),
            SIMD3(0, Float(h), 0)
        ]
        let base = vertices.count
        for point in local {
            let world = surface.transform * SIMD4<Float>(point.x, point.y, point.z, 1)
            vertices.append(Vertex(
                x: Double(world.x),
                y: Double(world.y),
                z: Double(world.z),
                r: color.0, g: color.1, b: color.2
            ))
        }
        faces.append([base, base + 1, base + 2])
        faces.append([base, base + 2, base + 3])
    }

    private static func appendBox(
        vertices: inout [Vertex],
        faces: inout [[Int]],
        object: CapturedRoom.Object
    ) {
        let half = SIMD3<Float>(
            object.dimensions.x / 2,
            object.dimensions.y / 2,
            object.dimensions.z / 2
        )
        guard half.x > 0.001, half.y > 0.001, half.z > 0.001 else { return }

        let corners: [SIMD3<Float>] = [
            SIMD3(-half.x, -half.y, -half.z),
            SIMD3(half.x, -half.y, -half.z),
            SIMD3(half.x, half.y, -half.z),
            SIMD3(-half.x, half.y, -half.z),
            SIMD3(-half.x, -half.y, half.z),
            SIMD3(half.x, -half.y, half.z),
            SIMD3(half.x, half.y, half.z),
            SIMD3(-half.x, half.y, half.z)
        ]

        let base = vertices.count
        for corner in corners {
            let world = object.transform * SIMD4<Float>(corner.x, corner.y, corner.z, 1)
            vertices.append(Vertex(
                x: Double(world.x),
                y: Double(world.y),
                z: Double(world.z),
                r: 238, g: 210, b: 170
            ))
        }

        let boxFaces: [[Int]] = [
            [0, 2, 1], [0, 3, 2],
            [4, 5, 6], [4, 6, 7],
            [0, 1, 5], [0, 5, 4],
            [1, 2, 6], [1, 6, 5],
            [2, 3, 7], [2, 7, 6],
            [3, 0, 4], [3, 4, 7]
        ]
        for face in boxFaces {
            faces.append(face.map { base + $0 })
        }
    }

    private static func appendTriangulatedFan(base: Int, count: Int, to faces: inout [[Int]]) {
        guard count >= 3 else { return }
        for index in 1..<(count - 1) {
            faces.append([base, base + index, base + index + 1])
        }
    }

    private static func format(_ value: Double) -> String {
        if abs(value) < 0.0001 { return "0" }
        return String(format: "%.4f", value)
    }
}
